apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openebs
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/KSmigielski/truenas-k8s

  destinations:
  - namespace: openebs
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: "*"

  namespaceResourceWhitelist:
  - group: '*'
    kind: "*"
