apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
spec:
  parentRefs:
  - name: eg
  hostnames:
  - "argocd.homelab.local"
  rules:
  - backendRefs:
    - name: bootstrap-argocd-server
      port: 8080
