apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-dns-unbound
  labels:
    app.kubernetes.io/name: unbound
    app.kubernetes.io/component: local-dns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound
      app.kubernetes.io/component: local-dns
  template:
    metadata:
      name: local-dns-unbound
      labels:
        app.kubernetes.io/name: unbound
        app.kubernetes.io/component: local-dns
    spec:
      serviceAccountName: local-dns-unbound
      
      containers:
        - name: unbound
          image: docker.io/savepointsam/unbound:1.15.0
          imagePullPolicy: IfNotPresent
          env:
          envFrom:
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
          ports:
            - name: dns
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - "drill"
                - "@127.0.0.1"
                - "cloudflare.com"
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - "drill"
                - "@127.0.0.1"
                - "cloudflare.com"
          volumeMounts:
            - name: config-volume
              mountPath: /opt/unbound/etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: config-volume
              mountPath: /opt/unbound/etc/unbound/forward-records.conf
              subPath: forward-records.conf
            - name: config-volume
              mountPath: /opt/unbound/etc/unbound/a-records.conf
              subPath: a-records.conf
      volumes:
        - name: config-volume
          configMap:
            name: local-dns-unbound-config

