apiVersion: v1
kind: Service
metadata:
  name: local-dns-unbound
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    name: local-dns-unbound
