apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: vm
spec:
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    isDefault: true
    type: victoriametrics-datasource
    name: VictoriaMetrics
    url: http://vmselect-vm.vm.svc:8481/select/0/prometheus
  instanceSelector:
    matchLabels:
      grafana: grafana
