metallb:
  # Default values for metallb.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  loadBalancerClass: ""
  
  # To configure MetalLB, you must specify ONE of the following two
  # options.
  
  rbac:
    # create specifies whether to install and use RBAC rules.
    create: true
  
  prometheus:
    # port both controller and speaker will listen on for metrics
    metricsPort: 7472
  
    # the image to be used for the kuberbacproxy container
    rbacProxy:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.12.0
      pullPolicy:
  
  # controller contains configuration specific to the MetalLB cluster
  # controller.
  controller:
    enabled: true
    # -- Controller log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
    logLevel: info
    # command: /controller
    # webhookMode: enabled
    image:
      repository: quay.io/metallb/controller
      tag:
      pullPolicy:
    ## @param controller.updateStrategy.type Metallb controller deployment strategy type.
    ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
    ## e.g:
    ## strategy:
    ##  type: RollingUpdate
    ##  rollingUpdate:
    ##    maxSurge: 25%
    ##    maxUnavailable: 25%
    ##
    strategy:
      type: RollingUpdate
    serviceAccount:
      # Specifies whether a ServiceAccount should be created
      create: true
      # The name of the ServiceAccount to use. If not set and create is
      # true, a name is generated using the fullname template
      name: ""
      annotations: {}
    securityContext:
      runAsNonRoot: true
      # nobody
      runAsUser: 65534
      fsGroup: 65534
    resources: {}
      # limits:
        # cpu: 100m
        # memory: 100Mi
    nodeSelector: {}
    tolerations: []
    priorityClassName: ""
    runtimeClassName: ""
    affinity: {}
    podAnnotations: {}
    labels: {}
    livenessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    tlsMinVersion: "VersionTLS12"
    tlsCipherSuites: ""
  
    extraContainers: []
  
  # speaker contains configuration specific to the MetalLB speaker
  # daemonset.
  speaker:
    enabled: true
    # command: /speaker
    # -- Speaker log level. Must be one of: `all`, `debug`, `info`, `warn`, `error` or `none`
    logLevel: info
    tolerateMaster: true
    memberlist:
      enabled: true
      mlBindPort: 7946
      mlBindAddrOverride: ""
      mlSecretKeyPath: "/etc/ml_secret_key"
    excludeInterfaces:
      enabled: true
    # ignore the exclude-from-external-loadbalancer label
    ignoreExcludeLB: false
  
    image:
      repository: quay.io/metallb/speaker
      tag:
      pullPolicy:
    ## @param speaker.updateStrategy.type Speaker daemonset strategy type
    ## ref: https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
    ##
    updateStrategy:
      ## StrategyType
      ## Can be set to RollingUpdate or OnDelete
      ##
      type: RollingUpdate
    serviceAccount:
      # Specifies whether a ServiceAccount should be created
      create: true
      # The name of the ServiceAccount to use. If not set and create is
      # true, a name is generated using the fullname template
      name: ""
      annotations: {}
    securityContext: {}
    ## Defines a secret name for the controller to generate a memberlist encryption secret
    ## By default secretName: {{ "metallb.fullname" }}-memberlist
    ##
    # secretName:
    resources: {}
      # limits:
        # cpu: 100m
        # memory: 100Mi
    nodeSelector: {}
    tolerations: []
    priorityClassName: ""
    affinity: {}
    ## Selects which runtime class will be used by the pod.
    runtimeClassName: ""
    podAnnotations: {}
    labels: {}
    livenessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 5
    # frr contains configuration specific to the MetalLB FRR container,
    # for speaker running alongside FRR.
    frr:
      enabled: true
      image:
        repository: quay.io/frrouting/frr
        tag: 9.0.2
        pullPolicy:
      metricsPort: 7473
      resources: {}
  
      # if set, enables a rbac proxy sidecar container on the speaker to
      # expose the frr metrics via tls.
      # secureMetricsPort: 9121
  
  
    reloader:
      resources: {}
  
    frrMetrics:
      resources: {}
  
    extraContainers: []
  
  crds:
    enabled: true
    validationFailurePolicy: Fail
