apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: envoy-gateway

  source:
    repoURL: https://github.com/KSmigielski/truenas-k8s
    targetRevision: HEAD
    path: envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
    - CreateNamespace=true 
