apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: grafana

  source:
    repoURL: https://github.com/KSmigielski/truenas-k8s
    targetRevision: HEAD
    path: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
    - CreateNamespace=true 
