apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-dns
  namespace: argocd
spec:
  project: local-dns

  source:
    repoURL: https://github.com/KSmigielski/truenas-k8s
    targetRevision: HEAD
    path: local-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: local-dns

  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
      allowEmpty: false 
    syncOptions:
    - CreateNamespace=true 
