apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-dns-pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: local-dns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
      app.kubernetes.io/component: local-dns
  template:
    metadata:
      name: local-dns-pihole
      labels:
        app.kubernetes.io/name: pihole
        app.kubernetes.io/component: local-dns
    spec:
      serviceAccountName: local-dns-pihole
      
      containers:
        - name: pihole
          image: docker.io/pihole/pihole:2023.05.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Warsaw"
            - name: WEBPASSWORD_FILE
              valueFrom:
                secretKeyRef:
                  name: local-dns-pihole-webui-password
                  key: webpassword
            - name: PIHOLE_DNS_
              value: "1.1.1.1;1.0.0.1"
            - name: DNSSEC
              value: "false"
            - name: DNS_BOGUS_PRIV
              value: "true"
            - name: DNS_FQDN_REQUIRED
              value: "true"
            - name: REV_SERVER
              value: "false"
            - name: VIRTUAL_HOST
              value: ""
            - name: IPv6
              value: "true"
            - name: TEMPERATUREUNIT
              value: f
            - name: WEBUIBOXEDLAYOUT
              value: boxed
            - name: QUERY_LOGGING
              value: "true"
            - name: WEBTHEME
              value: default-auto
            - name: WEB_PORT
              value: ""
            - name: WEB_BIND_ADDR
              value: ""
            - name: CUSTOM_CACHE_SIZE
              value: "10000"
            - name: FTL_CMD
              value: "no-daemon"
            - name: ADMIN_EMAIL
              value: "admin"
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: dns
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /admin.index.php
              port: http
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /admin.index.php
              port: http
          volumeMounts:
            - name: pihole
              mountPath: /etc/pihole
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: local-dns-pihole

