apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-dns-pihole
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: local-dns
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
      app.kubernetes.io/component: local-dns
  template:
    metadata:
      name: local-dns-pihole
      labels:
        app.kubernetes.io/name: pihole
        app.kubernetes.io/component: local-dns
    spec:
      serviceAccountName: local-dns-pihole
      
      containers:
        - name: pihole
          image: docker.io/pihole/pihole:2024.05.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Warsaw"
            - name: WEBPASSWORD_FILE
              valueFrom:
                secretKeyRef:
                  name: local-dns-pihole-webui-password
                  key: webpassword
            - name: PIHOLE_DNS_
              value: "1.1.1.1;1.0.0.1"
            - name: DNS_BOGUS_PRIV
              value: "true"
            - name: DNS_FQDN_REQUIRED
              value: "true"
            - name: IPv6
              value: "true"
            - name: WEBTHEME
              value: high-contrast-dark
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - name: dns
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /admin/login.php
              port: http
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /admin/login.php
              port: http
          volumeMounts:
            - name: pihole
              mountPath: /etc/pihole
            - name: dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: local-dns-pihole
        - name: dnsmasq
          configMap:
            name: pihole
            items:
              - key: local.rules.dnsmasq
                path: local-subdomain.conf
