apiVersion: v1
kind: Service
metadata:
  name: local-dns-pihole
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    name: local-dns-pihole

